apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: digambar1234/mediclaim_project3
        name: springboot
        ports:
        - containerPort: 8080  
